service: easy-trekking-send-tourist-guide-invite
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: "*"
          Action:
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
  memorySize: 128
functions:
  app:
    handler: dist/handler.handler
    events:
      - eventBridge:
          name: event-bridge-easy-trekking-send-tourist-guide-invite
          description: Event bridge runned every day at mid nigth UTC+0 for send tourist guide invite
          schedule: cron(0 0 * * ? *)
          enabled: true
      - http:
          path: /
          method: GET
          cors: true
